### ISSUE TITLE
issue with _site/index.html overriding  all changes

### ISSUE THREAD

**Issue by rudolpha** [TaylanTatli/Halve#29]
hey,

so correct me if im wrong, but it seems like you have some code in the _site/index.html file that is overriding all other code. changing this code is fine, but each time i push the website to amazon s3, jekyll rebuilds the _site folder and i lose all local changes that ive made. maybe i'm missing a way to change these things outside of the index.html file? the first thing is making the posts page link to posts.html rather than taylantatli.github.io/Halve/posts and the second thing is the background home image for block-left of the homepage. hardcoded into index.html is the a href making posts link to this url: taylantatli.github.io/Halve/posts. hardcoded into index.html is also the background homepage image linking to another image on your github site. 

when i try to change these two things outside of _site folder, the changes dont apply because _site/index.html is overriding the changes. when i edit index.html then the changes only last for a short amount of time (enough time to push the website live). each time i restart terminal and sublimetext, jekyll has rebuilt index.html to its standard, problematic, overriding mode, which is quite frustrating.

any help would be appreciated.

**Comment by azharichenko** [comment]
First, the `_site/` folder is where Jekyll builds the site at so it will get **overridden everytime you rebuild** the project. If you want to edit the content of what will become `index.html` you need to edit `index.md`, the rest of `index.html` comes from `_layout/home.html` which outlines the layout of the home page.

Second, all the option details are contained within `_config.yml`. So to prevent the post going to `taylantatli.github.io/Halve/posts`, change line 4 of the `_config.yml` which has by default...

```
url: http://taylantatli.github.io/Halve
```

And lines 9-12 of `_config.yml` contains where it links the left block images, just simple add the images you want to the images folder and change the paths.

```
# Left Block Images
background:
  homepage: images/home.png                           # this image will be shown on homepage's left block
  post-list: images/unsplash-image-10.jpg             # this image will be shown on post list page
  default-post: images/unsplash-gallery-image-3.jpg   # this image will be shown when post's front matter doesn't specify any image
```

Finally, for Jekyll all the things you need to change in `_config.yml` and the various folders such as `_layouts/`, `_inlcudes/`, `_posts/`, `_data/`, etc.

Hopefully, this helps you out!
